"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Check, CheckCircle2, CircleX, Edit3, ShieldCheck } from "lucide-react";
import { api } from "@/lib/client/api";
import { categoryLabel, formatDate } from "@/lib/utils/format";
import type { BusinessCase, CaseAnalysis, DecisionRecord } from "@/lib/domain/types";

interface Entry extends DecisionRecord { case: BusinessCase | null; analysis: CaseAnalysis | null }
interface Result { decisions: Entry[]; totals: { all: number; approved: number; modified: number; rejected: number } }

export default function DecisionsPage() {
  const [data, setData] = useState<Result | null>(null);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");
  useEffect(() => { setLoading(true); api<Result>(`/api/decisions?action=${filter}`).then(setData).catch(() => undefined).finally(() => setLoading(false)); }, [filter]);
  return <div className="page-content">
    <div className="page-heading"><div><div className="page-eyebrow">Human-in-the-loop audit trail</div><h1 className="page-title">Decisions</h1><p className="page-description">Every approval, modification and rejection stays visible and accountable.</p></div><span className="badge badge-resolved"><ShieldCheck size={12} /> Operator control</span></div>
    <div className="metric-grid"><DecisionMetric label="Total decisions" value={data?.totals.all ?? 0} loading={loading} icon={<ShieldCheck size={15} />} /><DecisionMetric label="Approved" value={data?.totals.approved ?? 0} loading={loading} icon={<CheckCircle2 size={15} />} /><DecisionMetric label="Modified" value={data?.totals.modified ?? 0} loading={loading} icon={<Edit3 size={15} />} /><DecisionMetric label="Rejected" value={data?.totals.rejected ?? 0} loading={loading} icon={<CircleX size={15} />} /></div>
    <div className="filter-row"><select className="filter-select" value={filter} onChange={(e) => setFilter(e.target.value)} aria-label="Filter decisions"><option value="all">All decisions</option><option value="approve">Approved</option><option value="modify">Modified</option><option value="reject">Rejected</option></select><span style={{ color: "var(--foreground-muted)", fontSize: 10 }}>LISA recommends. Your team decides.</span></div>
    <section className="card card-pad"><div className="card-header" style={{ marginBottom: 13 }}><div><h2 className="card-title">Decision history</h2><p className="card-caption">Recommendations are advisory; people remain accountable for the action.</p></div></div>{loading ? <div style={{ display: "grid", gap: 9 }}>{[1,2,3].map((x) => <div className="loading-skeleton" key={x} style={{ height: 90 }} />)}</div> : data?.decisions.length ? <div style={{ display: "grid", gap: 9 }}>{data.decisions.map((item) => <article key={item.id} style={{ border: "1px solid var(--border)", borderRadius: 11, padding: "13px 14px" }}><div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}><div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}><div className="activity-icon">{item.action === "approve" ? <Check size={14} /> : item.action === "modify" ? <Edit3 size={13} /> : <CircleX size={14} />}</div><div><div style={{ display: "flex", alignItems: "center", flexWrap: "wrap", gap: 7 }}><span className={`badge ${item.action === "approve" ? "badge-resolved" : item.action === "reject" ? "badge-critical" : "badge-awaiting"}`}>{item.action}</span>{item.case && <span style={{ color: "var(--foreground-muted)", fontSize: 9 }}>{item.case.ref} · {categoryLabel(item.case.category)}</span>}</div><Link href={item.case ? `/cases/${item.case.id}` : "/cases"} className="case-title-link" style={{ display: "inline-block", marginTop: 7 }}>{item.case?.title ?? "Case no longer available"}</Link><div style={{ marginTop: 5, color: "var(--foreground-secondary)", fontSize: 10 }}>{item.modifiedRecommendation?.action ?? item.analysis?.recommendation.action ?? "No recommendation attached"}</div>{item.note && <p style={{ margin: "6px 0 0", color: "var(--foreground-muted)", fontSize: 9, lineHeight: 1.6 }}>“{item.note}”</p>}</div></div><div style={{ flex: "none", color: "var(--foreground-muted)", fontSize: 9, textAlign: "right" }}>{formatDate(item.createdAt)}<div style={{ marginTop: 4 }}>by {item.operator}</div></div></div><div style={{ display: "flex", justifyContent: "flex-end", marginTop: 7 }}><Link href={item.case ? `/cases/${item.case.id}` : "/cases"} className="btn btn-ghost btn-sm">Review case <ArrowRight size={12} /></Link></div></article>)}</div> : <div className="empty-state"><span className="empty-state-icon"><ShieldCheck size={20} /></span><h3>No decisions recorded</h3><p>After LISA analyzes a case, your team can approve, modify or reject the recommendation. Every choice is recorded here.</p><Link href="/cases" className="btn btn-primary btn-sm">Review open cases <ArrowRight size={12} /></Link></div>}</section>
  </div>;
}
function DecisionMetric({ label, value, loading, icon }: { label: string; value: number; loading: boolean; icon: React.ReactNode }) { return <article className="card metric-card"><div className="metric-top">{label}<span className="metric-icon">{icon}</span></div>{loading ? <div className="loading-skeleton" style={{ width: 50, height: 24, marginTop: 13 }} /> : <div className="metric-value">{value}</div>}</article>; }
