"use client";

import { useEffect, useState } from "react";
import { Activity, Brain, CheckCircle2, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "@/lib/client/api";

interface Data { metrics: { totalCases: number; openCases: number; resolvedCases: number; successRate: number; averageResolutionHours: number; memoryCount: number; successRateChange: number }; trend: Array<{ label: string; cases: number; resolved: number; successRate: number }>; categoryCounts: Array<{ category: string; label: string; count: number }>; outcomeCounts: Array<{ outcome: string; count: number }>; lessonsByAction: Array<{ actionCategory: string; label: string; count: number; successRate: number }> }
const COLORS = ["#4c927d", "#8fbca8", "#d0aa67", "#c47c6b", "#8593b2"];

export default function AnalyticsPage() {
  const [data, setData] = useState<Data | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api<Data>("/api/analytics").then(setData).catch(() => undefined).finally(() => setLoading(false)); }, []);
  const metrics = data?.metrics;
  const outcomes = data?.outcomeCounts.filter((x) => x.count > 0) ?? [];
  return <div className="page-content">
    <div className="page-heading"><div><div className="page-eyebrow">Measure what matters</div><h1 className="page-title">Operations analytics</h1><p className="page-description">Case health, customer outcomes and the impact of learning over time.</p></div><span className="badge badge-resolved">Updated just now</span></div>
    <div className="metric-grid"><Metric title="Cases handled" value={metrics?.totalCases} icon={<Activity size={15} />} loading={loading} foot={`${metrics?.openCases ?? 0} still open`} /><Metric title="Resolved" value={metrics?.resolvedCases} icon={<CheckCircle2 size={15} />} loading={loading} foot="Across all recorded cases" /><Metric title="Positive outcome rate" value={metrics ? `${Math.round(metrics.successRate * 100)}%` : "—"} icon={<TrendingUp size={15} />} loading={loading} foot={`${metrics?.successRateChange ?? 0 >= 0 ? "+" : ""}${metrics?.successRateChange ?? 0} pts vs. prior period`} /><Metric title="Learning signals" value={metrics?.memoryCount} icon={<Brain size={15} />} loading={loading} foot="Outcomes added to memory" /></div>
    <div className="dashboard-grid">
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Weekly case flow</h2><p className="card-caption">New cases and resolutions over the last 7 weeks</p></div></div><div className="chart-wrap" style={{ height: 270 }}>{loading ? <div className="loading-skeleton" style={{ height: "100%" }} /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={data?.trend} margin={{ top: 8, right: 9, left: -18, bottom: 0 }}><defs><linearGradient id="analyticsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3c8874" stopOpacity={.18} /><stop offset="100%" stopColor="#3c8874" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "var(--foreground-muted)", fontSize: 9 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "var(--foreground-muted)", fontSize: 9 }} /><Tooltip contentStyle={{ border: "1px solid var(--border)", borderRadius: 9, background: "var(--surface)", color: "var(--foreground)", fontSize: 10 }} /><Area type="monotone" dataKey="cases" name="New cases" stroke="#37816f" fill="url(#analyticsFill)" strokeWidth={2} /><Area type="monotone" dataKey="resolved" name="Resolved" stroke="#a6cbb9" fill="transparent" strokeWidth={2} /></AreaChart></ResponsiveContainer>}</div></section>
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Resolution outcomes</h2><p className="card-caption">Honest results from closed cases</p></div></div>{outcomes.length ? <div style={{ height: 245, position: "relative", marginTop: 8 }}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={outcomes} dataKey="count" nameKey="outcome" innerRadius={61} outerRadius={88} paddingAngle={4} stroke="none">{outcomes.map((entry, i) => <Cell key={entry.outcome} fill={entry.outcome === "failure" ? "#c1786d" : entry.outcome === "partial" ? "#d6ae66" : entry.outcome === "unknown" ? "#99a4b4" : COLORS[i % COLORS.length]} />)}</Pie><Tooltip contentStyle={{ border: "1px solid var(--border)", borderRadius: 9, background: "var(--surface)", color: "var(--foreground)", fontSize: 10 }} /></PieChart></ResponsiveContainer><div style={{ position: "absolute", inset: "50% auto auto 50%", transform: "translate(-50%,-50%)", textAlign: "center" }}><div style={{ fontSize: 22, fontWeight: 770 }}>{metrics?.resolvedCases ?? 0}</div><div style={{ color: "var(--foreground-muted)", fontSize: 9 }}>resolved</div></div></div> : <div className="empty-state" style={{ padding: 43 }}><span className="empty-state-icon"><CheckCircle2 size={18} /></span><h3>No outcomes yet</h3><p>Resolved cases will appear after operators record what actually happened.</p></div>}<div style={{ display: "flex", flexWrap: "wrap", justifyContent: "center", gap: 12 }}>{outcomes.map((item, i) => <div key={item.outcome} style={{ display: "flex", alignItems: "center", gap: 5, color: "var(--foreground-secondary)", fontSize: 9 }}><span style={{ width: 7, height: 7, borderRadius: 3, background: item.outcome === "failure" ? "#c1786d" : item.outcome === "partial" ? "#d6ae66" : item.outcome === "unknown" ? "#99a4b4" : COLORS[i % COLORS.length] }} />{item.outcome} · {item.count}</div>)}</div></section>
    </div>
    <div className="bottom-grid">
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Case volume by category</h2><p className="card-caption">Top-level operational mix</p></div></div><div style={{ height: 270, marginTop: 15 }}>{data?.categoryCounts.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data.categoryCounts} layout="vertical" margin={{ top: 0, right: 22, left: 2, bottom: 0 }}><CartesianGrid horizontal={false} stroke="var(--border)" strokeDasharray="3 4" /><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "var(--foreground-muted)", fontSize: 9 }} /><YAxis type="category" dataKey="label" width={115} tickLine={false} axisLine={false} tick={{ fill: "var(--foreground-secondary)", fontSize: 9 }} /><Tooltip contentStyle={{ border: "1px solid var(--border)", borderRadius: 9, background: "var(--surface)", color: "var(--foreground)", fontSize: 10 }} /><Bar dataKey="count" name="Cases" fill="#4f967e" radius={[0,5,5,0]} barSize={13} /></BarChart></ResponsiveContainer> : <div className="empty-state"><p>No cases to chart yet.</p></div>}</div></section>
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">What actions work?</h2><p className="card-caption">Actual outcome by action type</p></div></div>{data?.lessonsByAction.length ? <div className="category-list">{data.lessonsByAction.slice(0, 7).map((item) => <div className="category-row" key={item.actionCategory}><span className="category-name">{item.label} <span style={{ color: "var(--foreground-muted)" }}>· {item.count}</span></span><span className="category-count">{item.successRate}%</span><div className="progress-track"><div className="progress-fill" style={{ width: `${item.successRate}%`, background: item.successRate < 40 ? "#c1786d" : undefined }} /></div></div>)}</div> : <div className="empty-state"><span className="empty-state-icon"><Brain size={18} /></span><h3>Learning starts with outcomes</h3><p>Record a resolution outcome to build action-level evidence.</p></div>}</section>
    </div>
    <p style={{ marginTop: 14, color: "var(--foreground-muted)", fontSize: 9 }}>Charts use case and operator-reported outcome records. Outcomes are not inferred by LISA.</p>
  </div>;
}
function Metric({ title, value, icon, loading, foot }: { title: string; value?: number | string; icon: React.ReactNode; loading: boolean; foot: string }) { return <article className="card metric-card"><div className="metric-top">{title}<span className="metric-icon">{icon}</span></div>{loading ? <div className="loading-skeleton" style={{ width: 72, height: 25, marginTop: 12 }} /> : <div className="metric-value">{value ?? 0}</div>}<div className="metric-foot">{foot}</div></article>; }
