"use client";

import Link from "next/link";
import { BookOpen, Brain, CheckCircle2, ChevronRight, CircleHelp, FileText, ShieldCheck, Sparkles, Zap } from "lucide-react";

const sections = [
  { icon: <Brain size={16} />, title: "What LISA remembers", detail: "LISA stores resolved cases with the decision, action taken, verified outcome and the lesson. Similar experiences are retrieved when a new case is analyzed.", tag: "Memory" },
  { icon: <ShieldCheck size={16} />, title: "Human approval is required", detail: "Every recommendation is advisory. LISA never issues a refund, contacts a customer, changes an order or executes an operational action. An operator approves, modifies or rejects it.", tag: "Safety" },
  { icon: <CheckCircle2 size={16} />, title: "Record what actually happened", detail: "After the operator acts, record success, partial, failure or unknown with an outcome note. A decision alone is not evidence that the action worked.", tag: "Learning loop" },
  { icon: <Sparkles size={16} />, title: "Why similar cases matter", detail: "LISA shows the closest resolved cases, their outcomes and the evidence that informed its recommendation. Local fallback retrieval is lexical; connect Hindsight for multi-strategy semantic, keyword, graph and temporal recall.", tag: "Transparency" },
  { icon: <Zap size={16} />, title: "Local demo vs. production providers", detail: "Without credentials, LISA runs a deterministic rules baseline, local file storage and embedded lexical memory. Configure Groq, Hindsight, PostgreSQL and Redis for production-grade providers. The UI labels which mode is active.", tag: "Providers" },
  { icon: <FileText size={16} />, title: "Import existing cases", detail: "POST a JSON array of up to 100 cases to /api/import. Required fields: title and description; category, priority, customer and source are optional. Validate and sanitize your source system data before importing.", tag: "Integrations" },
];

export default function KnowledgePage() {
  return <div className="page-content">
    <div className="page-heading"><div><div className="page-eyebrow">LISA, explained</div><h1 className="page-title">Knowledge base</h1><p className="page-description">How to get useful, explainable and safe learning from your operations agent.</p></div><span className="badge badge-resolved"><BookOpen size={12} /> Product guide</span></div>
    <section className="card card-pad" style={{ marginBottom: 15, background: "linear-gradient(135deg,var(--surface),var(--accent-soft))" }}><div style={{ maxWidth: 730 }}><div className="recommendation-label"><Sparkles size={13} /> The core idea</div><h2 style={{ margin: "10px 0 7px", fontSize: 18, letterSpacing: "-.035em" }}>Experience is the product.</h2><p style={{ margin: 0, color: "var(--foreground-secondary)", fontSize: 11, lineHeight: 1.8 }}>LISA is a business operations agent whose value compounds: retrieve relevant precedent, explain the evidence, help an operator make a decision, and remember the real outcome. The feedback loop—not just a chat box—is the product.</p><div style={{ display: "flex", gap: 8, marginTop: 15 }}><Link href="/cases" className="btn btn-primary btn-sm">Open cases <ChevronRight size={12} /></Link><Link href="/memory" className="btn btn-sm">Explore memory</Link></div></div></section>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 13 }}>{sections.map((section) => <article className="card card-pad" key={section.title}><div className="card-header"><div style={{ display: "flex", alignItems: "center", gap: 9 }}><span className="metric-icon">{section.icon}</span><h2 className="card-title">{section.title}</h2></div><span className="badge badge-medium">{section.tag}</span></div><p style={{ margin: "13px 0 0", color: "var(--foreground-secondary)", fontSize: 10, lineHeight: 1.75 }}>{section.detail}</p></article>)}</div>
    <section className="card card-pad" style={{ marginTop: 15 }}><div className="card-header"><div><h2 className="card-title">A good 60-second demonstration</h2><p className="card-caption">Show the difference between a chatbot and a learning agent.</p></div><CircleHelp size={15} color="var(--accent)" /></div><ol className="step-list" style={{ marginTop: 16 }}><li><span className="step-num">1</span>Open the unresolved delivery case and ask LISA to analyze it.</li><li><span className="step-num">2</span>Review the similar cases, including a successful priority reship and a failed premature refund.</li><li><span className="step-num">3</span>Approve or modify the recommendation. Resolve the case with the outcome and a concrete note.</li><li><span className="step-num">4</span>Create a similar delivery case. LISA recalls the newly retained experience and explains how it affected confidence or action choice.</li><li><span className="step-num">5</span>Show the Memory and Decisions pages: the evidence, human action and result are all auditable.</li></ol></section>
    <p style={{ marginTop: 14, color: "var(--foreground-muted)", fontSize: 9 }}>Production deployment requires secure authentication, a persistent PostgreSQL instance and provider secrets stored in your hosting platform’s secret manager.</p>
  </div>;
}
