"use client";

import { useEffect, useState } from "react";
import { Database, KeyRound, Moon, Save, Server, ShieldCheck, Sparkles, Sun, Zap } from "lucide-react";
import { api, jsonBody } from "@/lib/client/api";
import { useShell } from "@/components/app-shell";

interface Settings { businessName: string; operatorName: string; slaHours: Record<string, number>; autoAnalyze: boolean; memoryEnabled: boolean; theme: "light" | "dark" | "system" }
interface System { app: { environment: string; version: string; uptimeSeconds: number }; services: { database: { ok: boolean; driver: string; latencyMs: number; error?: string }; memory: { configured: boolean; ok: boolean; provider: string; mode: string; latencyMs?: number; error?: string }; cache: { ok: boolean; mode: string }; groq: { configured: boolean; provider: string } } }

export default function SettingsPage() {
  const shell = useShell();
  const [settings, setSettings] = useState<Settings | null>(null);
  const [system, setSystem] = useState<System | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { api<{ settings: Settings; system: System }>("/api/settings").then((result) => { setSettings(result.settings); setSystem(result.system); }).catch((error) => shell?.showToast(error.message, "error")).finally(() => setLoading(false)); }, [shell]);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings((prev) => prev ? { ...prev, [key]: value } : prev);
  const save = async () => {
    if (!settings) return;
    setSaving(true);
    try { const result = await api<{ settings: Settings }>("/api/settings", { method: "PATCH", body: jsonBody(settings) }); setSettings(result.settings); shell?.showToast("Settings saved"); window.dispatchEvent(new Event("lisa:refresh")); }
    catch (error) { shell?.showToast(error instanceof Error ? error.message : "Could not save settings", "error"); }
    finally { setSaving(false); }
  };
  const setTheme = (theme: "light" | "dark" | "system") => {
    update("theme", theme);
    window.dispatchEvent(new CustomEvent("lisa:theme", { detail: { theme } }));
  };

  return <div className="page-content">
    <div className="page-heading"><div><div className="page-eyebrow">Make LISA your own</div><h1 className="page-title">Settings</h1><p className="page-description">Workspace preferences, response service levels and system health.</p></div><button className="btn btn-primary" disabled={!settings || saving} onClick={() => void save()}><Save size={14} />{saving ? "Saving…" : "Save changes"}</button></div>
    {loading ? <div className="loading-skeleton" style={{ height: 350 }} /> : settings && <div className="settings-grid">
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Workspace preferences</h2><p className="card-caption">Customize the operator experience.</p></div><Sparkles size={15} color="var(--accent)" /></div><div style={{ display: "grid", gap: 12, marginTop: 17 }}><div className="field"><label htmlFor="business-name">Business name</label><input id="business-name" maxLength={120} value={settings.businessName} onChange={(e) => update("businessName", e.target.value)} /></div><div className="field"><label htmlFor="operator-name">Your name</label><input id="operator-name" maxLength={120} value={settings.operatorName} onChange={(e) => update("operatorName", e.target.value)} /></div><div className="field"><label>Appearance</label><div style={{ display: "flex", gap: 7 }}>{(["light", "dark", "system"] as const).map((theme) => <button type="button" key={theme} className={`btn btn-sm ${settings.theme === theme ? "btn-primary" : ""}`} onClick={() => setTheme(theme)}>{theme === "light" ? <Sun size={12} /> : theme === "dark" ? <Moon size={12} /> : <Sparkles size={12} />}{theme}</button>)}</div></div></div><div className="setting-row"><div><strong>Memory enabled</strong><span>Retrieve past experience during analysis and chat.</span></div><button aria-label="Toggle memory" aria-pressed={settings.memoryEnabled} className={`toggle ${settings.memoryEnabled ? "on" : ""}`} onClick={() => update("memoryEnabled", !settings.memoryEnabled)} /></div><div className="setting-row"><div><strong>Auto-analyze new cases</strong><span>When enabled, LISA starts analysis immediately after case creation.</span></div><button aria-label="Toggle auto-analyze" aria-pressed={settings.autoAnalyze} className={`toggle ${settings.autoAnalyze ? "on" : ""}`} onClick={() => update("autoAnalyze", !settings.autoAnalyze)} /></div></section>
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Response service levels</h2><p className="card-caption">Default target for the first operator response.</p></div><span className="badge badge-medium">Hours</span></div><div style={{ marginTop: 12 }}>{(["critical", "high", "medium", "low"] as const).map((priority) => <div className="setting-row" key={priority}><div><strong style={{ textTransform: "capitalize" }}>{priority} priority</strong><span>Suggested first-response target.</span></div><div style={{ display: "flex", alignItems: "center", gap: 6 }}><input aria-label={`${priority} SLA hours`} type="number" min={1} max={8760} value={settings.slaHours[priority] ?? 24} onChange={(e) => update("slaHours", { ...settings.slaHours, [priority]: Number(e.target.value) })} style={{ width: 70, height: 32, border: "1px solid var(--border)", borderRadius: 7, background: "var(--surface)", color: "var(--foreground)", textAlign: "center" }} /><span style={{ color: "var(--foreground-muted)", fontSize: 9 }}>h</span></div></div>)}</div></section>
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Connected services</h2><p className="card-caption">Provider state is visible; secrets are never displayed.</p></div><Server size={15} color="var(--accent)" /></div><div style={{ marginTop: 12 }}><Service icon={<Zap size={13} />} name="Language model" provider={system?.services.groq.provider ?? "Checking"} ok={system?.services.groq.configured ?? false} detail={system?.services.groq.configured ? "GROQ_API_KEY is configured" : "Using deterministic local rules"} /><Service icon={<Sparkles size={13} />} name="Long-term memory" provider={system?.services.memory.provider ?? "Checking"} ok={system?.services.memory.ok ?? false} detail={system?.services.memory.configured ? `Connected · ${system?.services.memory.latencyMs ?? 0}ms` : "Using local embedded lexical retrieval"} /><Service icon={<Database size={13} />} name="Application database" provider={system?.services.database.driver ?? "Checking"} ok={system?.services.database.ok ?? false} detail={system?.services.database.ok ? `Healthy · ${system?.services.database.latencyMs}ms` : system?.services.database.error ?? "Unavailable"} /><Service icon={<Server size={13} />} name="Cache and rate limits" provider={system?.services.cache.mode ?? "Checking"} ok={system?.services.cache.ok ?? false} detail="Single-instance local fallback is not shared across deployments" /></div><div style={{ marginTop: 13, borderRadius: 9, background: "var(--surface-muted)", padding: 11, color: "var(--foreground-muted)", fontSize: 9, lineHeight: 1.7 }}><KeyRound size={12} style={{ verticalAlign: "-2px", marginRight: 6 }} />Configure provider credentials in the hosting platform’s encrypted environment settings. Never add API keys to browser code or Git. Rotate any key that has been pasted into chat or committed.</div></section>
      <section className="card card-pad"><div className="card-header"><div><h2 className="card-title">Security & deployment</h2><p className="card-caption">Current runtime profile</p></div><ShieldCheck size={15} color="var(--accent)" /></div><div className="service-row"><span className="service-name">Environment</span><span className="status-text">{system?.app.environment ?? "—"}</span></div><div className="service-row"><span className="service-name">App version</span><span className="status-text">{system?.app.version ?? "—"}</span></div><div className="service-row"><span className="service-name">Authentication</span><span className="status-text">{shell?.authenticated ? "Authenticated" : "Not required"}</span></div><div className="service-row"><span className="service-name">Runtime</span><span className="status-text">Next.js · Node.js</span></div><p style={{ margin: "13px 0 0", color: "var(--foreground-muted)", fontSize: 9, lineHeight: 1.7 }}>For multi-instance production deployments, use PostgreSQL and Redis. Local file storage is intended for development and demos only. Configure LISA_API_TOKEN to protect the workspace.</p></section>
    </div>}
  </div>;
}
function Service({ icon, name, provider, ok, detail }: { icon: React.ReactNode; name: string; provider: string; ok: boolean; detail: string }) { return <div className="service-row"><div><div className="service-name">{icon}{name}</div><div style={{ marginTop: 5, marginLeft: 21, color: "var(--foreground-muted)", fontSize: 9 }}>{detail}</div></div><div style={{ display: "flex", alignItems: "center", gap: 6 }}><span className={`status-dot ${ok ? "" : "off"}`} /><span className="status-text">{provider}</span></div></div>; }
